//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFOpenIdConnectClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WCFOpenIdConnectClient.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angular-client.
        /// </summary>
        internal static string angularclient_aud_claim {
            get {
                return ResourceManager.GetString("angularclient_aud_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub.
        /// </summary>
        internal static string id_claim {
            get {
                return ResourceManager.GetString("id_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:8443/auth/realms/master.
        /// </summary>
        internal static string keycloak_authority {
            get {
                return ResourceManager.GetString("keycloak_authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_roles.
        /// </summary>
        internal static string keycloak_client_roles_claim {
            get {
                return ResourceManager.GetString("keycloak_client_roles_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string keycloak_name_claim {
            get {
                return ResourceManager.GetString("keycloak_name_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to realm_roles.
        /// </summary>
        internal static string keycloak_realm_roles_claim {
            get {
                return ResourceManager.GetString("keycloak_realm_roles_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service_roles.
        /// </summary>
        internal static string keycloak_service_roles_claim {
            get {
                return ResourceManager.GetString("keycloak_service_roles_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:8443/auth/realms/master/protocol/openid-connect/userinfo.
        /// </summary>
        internal static string oidc_userinfo_endpoint {
            get {
                return ResourceManager.GetString("oidc_userinfo_endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF-client.
        /// </summary>
        internal static string wcfservice_clientid {
            get {
                return ResourceManager.GetString("wcfservice_clientid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a9bc7aa1-d06a-491d-8f51-a7d28e017862.
        /// </summary>
        internal static string wcfservice_secret {
            get {
                return ResourceManager.GetString("wcfservice_secret", resourceCulture);
            }
        }
    }
}
